[project]
site_name = "ConfUSIus"
site_url = "https://samuel.diebolt.io/confusius/"
site_description = "Python package for analysis and visualization of functional ultrasound imaging data."
site_author = "Samuel Le Meur-Diebolt"
copyright = "Copyright Â© 2026 Samuel Le Meur-Diebolt"
docs_dir = "docs"
site_dir = "site"
repo_url = "https://github.com/sdiebolt/confusius"
repo_name = "sdiebolt/confusius"
edit_uri = "edit/main/docs/"
extra_css = ["stylesheets/extra.css"]
extra_javascript = [
    "javascripts/mathjax.js",
    "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
    "javascripts/mermaid.mjs",
]
nav = [
    { "Home" = "index.md" },
    { "User Guide" = [
        { "Getting Started" = "user-guide/getting-started.md" },
        { "Installation" = "user-guide/installation.md" },
        { "Input/Output" = "user-guide/io.md" },
        { "Beamformed IQ" = "user-guide/beamformed-iq.md" },
        { "Xarray Integration" = "user-guide/xarray.md" }
    ]},
    { "API Reference" = [
        { "Overview" = "api/index.md" },
        { "Input/Output" = "api/io.md" },
        { "Data Validation" = "api/validation.md"},
        { "Beamformed IQ" = "api/iq.md" },
        { "Plotting" = "api/plotting.md" },
        { "Quality Control" = "api/qc.md" },
        { "Registration" = "api/registration.md" },
        { "Signal Extraction" = "api/extract.md" },
        { "Signal Processing" = "api/signal.md" },
        { "Xarray Integration" = "api/xarray.md" },
    ]},
    { "Examples" = "examples/index.md" },
    { "Contributing" = "contributing.md" },
]

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/sdiebolt/confusius"
name = "ConfUSIus on GitHub"

[[project.extra.social]]
icon = "fontawesome/brands/python"
link = "https://pypi.org/project/confusius/"
name = "ConfUSIus on PyPI"

[project.theme]
variant = "modern"
language = "en"
features = [
    "navigation.tabs",
    "navigation.sections",
    "navigation.expand",
    "navigation.path",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.tracking",
    "toc.follow",
    "search.highlight",
    "content.code.copy",
    "content.code.annotate",
    "content.action.edit",
    "content.action.view",
    "content.tooltips",
    "content.footnote.tooltips"
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "custom"
accent = "custom"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.plugins.mkdocstrings.handlers.python]
inventories = [
    "https://docs.python.org/3/objects.inv",
    "https://numpy.org/doc/stable/objects.inv",
    "https://matplotlib.org/stable/objects.inv",
    "https://docs.scipy.org/doc/scipy/objects.inv",
    "https://docs.dask.org/en/stable/objects.inv",
    "https://docs.xarray.dev/en/stable/objects.inv",
    "https://zarr.readthedocs.io/en/stable/objects.inv",
    "https://rich.readthedocs.io/en/latest/objects.inv",
    "https://napari.org/stable/objects.inv",
    "https://nilearn.github.io/stable/objects.inv",
    "https://pandas.pydata.org/pandas-docs/stable/objects.inv",
    "https://nipype.readthedocs.io/en/latest/objects.inv"
]
paths = ["src"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "numpy"
docstring_section_style = "list"
members_order = "alphabetical"
separate_signature = true
show_source = false
filters = ["!^_"]
docstring_options = {ignore_init_summary = true, merge_init_into_class = true}
show_root_heading = true
show_root_toc_entry = true
show_root_full_path = false
show_object_full_path = false
show_category_heading = false
show_if_no_docstring = false
show_signature = true
show_signature_annotations = true
signature_crossrefs = true
annotations_path = "brief"
show_symbol_type_toc = true
inherited_members = true
parameter_headings = true
heading_level = 2
summary = true

[project.markdown_extensions.admonition]

[project.markdown_extensions.pymdownx.details]

[project.markdown_extensions.pymdownx.emoji]
emoji_index = "zensical.extensions.emoji.twemoji" 
emoji_generator = "zensical.extensions.emoji.to_svg"

[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" }
]

[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true

[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true

[project.markdown_extensions.pymdownx.inlinehilite]

[project.markdown_extensions.abbr]
[project.markdown_extensions.attr_list]
[project.markdown_extensions.pymdownx.snippets]
auto_append = ["docs/includes/abbreviations.md"]

[project.markdown_extensions.pymdownx.keys]

[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.tilde]

[project.markdown_extensions.toc]
toc_depth = 3
permalink = true

[project.markdown_extensions.md_in_html]

[project.markdown_extensions.footnotes]

[project.markdown_extensions.tables]

[project.markdown_extensions.def_list]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true
